backlog_file: .edpa/backlog.yaml
capacity: config/capacity.yaml
evidence:
  sources:
  - pattern: feat|fix|refactor|test|docs
    type: git_commits
  - pattern: '{type}/{ITEM_ID}-{description}'
    type: branch_naming
heuristics: config/cw_heuristics.yaml
iterations_dir: .edpa/iterations/
project: config/project.yaml
sync:
  auto_commit: true
  fields_mapping:
    bv: Business Value
    issue_type: Issue Type
    js: Job Size
    rr: Risk Reduction
    tc: Time Criticality
    team: Team
    wsjf: WSJF Score
  github_org: technomaton
  github_project_number: 4
  issue_types:
    Defect: Defekt v existující funkcionalitě
    Epic: Strategický cíl, 6-9 měsíců
    Feature: Musí se vejít do Planning Intervalu
    Initiative: Business case, investiční záměr
    Story: Dodáváno v iteraci
    Task: Technická práce
  sync_interval: 15m
